export enum RoutePaths {
    Empty = "",
    Login = "login",
    ChangePassword = "change-password",
    Admin = "admin",
    HomePage = "home-page",
    Universities = "universities",
    Users = "users",
    NewsItems = "news-items",
    Documents = "documents",
    ErasmusPage = "erasmus-page",
    MobilityStudentsStudyPage = "mobility-students/study-page",
    MobilityStudentsPracticePage = "mobility-students/practice-page",
    MobilityAdministrationStudyPage = "mobility-administration/study-page",
    MobilityAdministrationPracticePage = "mobility-administration/practice-page",
    ProjectsPage = "projects-page",
    CreditMobilityInfo = "credit-mobility/info",
    CreditMobilityApplication = "credit-mobility/application",
    CreditMobilityPartners = "credit-mobility/partners",
    CreditMobilityStaffTraining = "credit-mobility/staff-training",
    CreditMobilityStudentMobility = "credit-mobility/student-mobility",
    CreditMobilityTeachingMobility = "credit-mobility/teaching-mobility",
}
